on: [push]

jobs:
  build:
    name: Run unit and integration tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.7
          java-package: jdk
          architecture: x64
      - name: maven build
        run: |
          chmod +x mvnw
          ./mvnw package
  package:
    name: Build and Push Docker Image
    needs: [build]
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build Docker image
        run: ./mvnw spring-boot:build-image
      - name: Push to Docker Hub
        run: docker push ashitikov7/catalog-service:0.0.1-SNAPSHOT
